tinyMCE.addI18n('de.emotions_dlg',{
title:"Smiley einfügen",
desc:"Smileys",
confused:"Verwirrt",
cool:"Cool",
cry:"Schreiend",
eek:"Eek",
embarassed:"Verlegen",
evil:"Böse",
frown:"Stirnrunzelnd",
grin:"Grinsend",
laughing:"Lachend",
mad:"verrückt",
neutral:"Neutral",
roll:"Rollende Augen",
sad:"traurig",
smile:"lächelnd",
surprised:"überrascht",
tongue_out:"Zunge raus",
wink:"zwinkernd",
yell:"schreiend"
});
