tinyMCE.addI18n('de.fullpage_dlg',{
title:"Dokumenteigenschaften",
meta_tab:"Allgemein",
appearance_tab:"Aussehen",
advanced_tab:"Erweitert",
meta_props:"Metainformation",
langprops:"Sprache und Kodierung",
meta_title:"Titel",
meta_keywords:"Schlüsselworte",
meta_description:"Beschreibung",
meta_robots:"Robots",
doctypes:"Dokumententyp",
langcode:"Sprachcode",
langdir:"Schreibrichtung",
ltr:"Links nach Rechts",
rtl:"Rechts nach links",
xml_pi:"XML-Manifest",
encoding:"Zeichenkodierung",
appearance_bgprops:"Hintergrundeigenschaften",
appearance_marginprops:"Inhalt-Ränder",
appearance_linkprops:"Linkfarbe",
appearance_textprops:"Texteigenschaften",
bgcolor:"Hintergrundfarbe",
bgimage:"Hintergrundbild",
left_margin:"Linker Rand",
right_margin:"Rechter Rand",
top_margin:"Oberer Rand",
bottom_margin:"Unterer Rand",
text_color:"Textfarbe",
font_size:"Schriftgröße",
font_face:"Schriftschnitt",
link_color:"Linkfarbe",
hover_color:"Hoverfarbe",
visited_color:"Besucht Farbe",
active_color:"Aktivlink-Farbe",
textcolor:"Farbe",
fontsize:"Schriftgröße",
fontface:"Schriftfamilie",
meta_index_follow:"Indizieren und Links folgen",
meta_index_nofollow:"Indizieren aber Links nicht folgen",
meta_noindex_follow:"nicht Indizieren, aber Links folgen",
meta_noindex_nofollow:"nicht Indizieren und Links nicht folgen",
appearance_style:"Stilvorlage und Eigenschaften",
stylesheet:"Stilvorlage",
style:"Stil",
author:"Autor",
copyright:"Copyright",
add:"Neues Element hinzufügen",
remove:"Gewähltes Element entfernen",
moveup:"Gewähltes Element nach oben schieben",
movedown:"gewähltes Element nach unten schieben",
head_elements:"Kopf-Elemente",
info:"Information",
add_title:"Titel-Element",
add_meta:"Meta-Element",
add_script:"Script-Element",
add_style:"Stil-Element",
add_link:"Link-Element",
add_base:"Grund-Element",
add_comment:"Kommentar hinzufügen",
title_element:"Titel-Element",
script_element:"Script-Element",
style_element:"Stil-Element",
base_element:"Grund-Element",
link_element:"Link-Element",
meta_element:"Meta-Element",
comment_element:"Kommentieren",
src:"Src",
language:"Sprache",
href:"Href",
target:"Ziel",
type:"Typ",
charset:"Charset",
defer:"Defer",
media:"Media",
properties:"Eigenschaften",
name:"Name",
value:"Wert",
content:"Inhalt",
rel:"Rel",
rev:"Rev",
hreflang:"Href lang",
general_props:"Allgemein",
advanced_props:"Erweitert"
});